docs/add_compute_node.rst
kubespray/roles/kubernetes/kubeadm/defaults/main.yml
kubespray/roles/kubernetes/kubeadm/tasks/main.yml
kubespray/scale.yml

There is a problem with joining node when --anonymous-auth is false in kube-apiserver.
Kubeadm uses token-based discovery but it needs anonymous auth on kube-apiserver to get cluster information.
So I added file-based discovery so that a node can join the cluster with it.

Feature/no ref/kubeadm join anonymous auth false

---

roles/burrito.localrepo/tasks/main.yml

- feature: add genesis registry to serve local registry image
- refactor: move offline vars from vars.yml to offline_vars.yml
- hotfix: do not remove offline_flag; add head -1 to get the repo/registry pids
- fix: add the first controller ip bind in haproxy setup on localrepo role

fix: add first controller ip in localrepo section of haproxy

---

vars.yml.sample

the default is not set up keepalived service interface VIP

feature: make keepalived service vip optional

---

vars.yml.sample

changed is_ovs default value from true to false; linuxbridge is the default ML2 now.

fix: set is_ovs to false

---

README.rst
README_offline.rst
kubespray/roles/burrito.openstack/templates/btx.yml.j2
scripts/images.txt
vars.yml.sample

* btx modifications
- add provider-network-only VM creation option in btx --test.
and make it the default option.
- add --selfservice option to create a VM with private network and
floating ip.
* burrito modifications
- add btx.version to 1.0.0 in vars.yml.sample
- use btx.version in kubespray/roles/burrito.openstack/templates/btx.yml.j2
- change btx image tag to 1.0.0 in scripts/images.txt

feature: update btx to 1.0.0

---

openstack-helm-infra/rabbitmq/templates/bin/_rabbitmq-start.sh.tpl

현재 rabbitmq에서 권장하지 않는 health check를 사용하고있어 수정하였습니다.
현재 사용중인 health check 방식의 경우 resource를 많이 잡아먹으며, 오탐이 발생하기 쉽다고 공식Docs에서는 이야기하고 있습니다. 따라서 조금 더 오탐확률이 적은 health check로 수정하였습니다.
( rabbitmq docs:: https://www.rabbitmq.com/monitoring.html )

Rabbitmq start.sh 수정

---

kubespray/roles/burrito.openstack/defaults/main.yml
kubespray/roles/burrito.openstack/templates/osh/barbican.yml.j2

kek setup in simple_crypto_plugin section of barbican.conf

feature: add randomly generated kek in barbican.conf

---

roles/burrito.genesisregistry/defaults/main.yml
scripts/bin.txt
scripts/images.txt
vars.yml.sample

fix: update registry tarball and image to 2.8.2; fix: CVE-2023-2253 runaway allocation on /v2/_catalog

fix: update registry tarball and image to 2.8.2

---

patches/09-patch-kubespray-registry-template-registry-rs-yaml.txt

This is a regression bug. Burrito 1.1.3 has nodeSelector in registry replicaset. But it was removed in 1.2.0 when migrating kubespray to upstream version.

fix: patch registry replicaset to add nodeSelector

---

roles/burrito.ceph-csi/defaults/main.yml
roles/burrito.ceph-csi/templates/06-csi-rbdplugin-provisioner.yaml.j2
roles/burrito.ceph-csi/templates/07-csi-rbdplugin.yaml.j2
roles/burrito.genesisregistry/defaults/main.yml
roles/burrito.genesisregistry/tasks/main.yml
vars.yml.sample

This is a deadlock bug.
When all control nodes are shut down and start,
the local registry and ceph-csi depends on each other so that they are in 
the deadlock situation.
To solve it, add ceph-csi images to genesis registry and ceph-csi gets images
from genesis registry.

fix: solve the deadlock between ceph-csi and local registry

---

roles/burrito.openstack/templates/osh/cinder.yml.j2

fix: add nas_secure_file* parameters in cinder netapp backend

fix: add nas_secure_file* parameters in cinder netapp backend

---

roles/burrito.openstack/templates/osh/cinder.yml.j2

fix: nas_secure_file_* typo in cinder.yml.j2

fix: nas_secure_file_* typo in cinder.yml.j2

---

roles/burrito.openstack/templates/osh/cinder.yml.j2
vars.yml.sample

feature: change cron_volume_usage_audit to false in cinder

feature: change cron_volume_usage_audit to false in cinder

---

netapp_vars.yml.tpl
roles/burrito.openstack/defaults/main.yml
roles/burrito.openstack/templates/osh/cinder.yml.j2
vars.yml.sample

fix: add burrito.openstack variables in defaults/main.yml

fix: add burrito.openstack variables in defaults/main.yml

---

templates/kube-apiserver.yaml.j2

fix: add tls-cipher-suite in kube-apiserver template

fix: add tls-cipher-suite in kube-apiserver template

---

roles/burrito.openstack/templates/osh_infra/ingress.yml.j2

fix: Set openstack ingress replicas to the number of control nodes

fix: Set openstack ingress replicas to the number of control nodes

---

openstack-helm/nova/templates/bin/_nova-console-compute-init.sh.tpl

fix(openstack): vnc listens on management interface only

fix(openstack): vnc listens on management interface only

---

roles/burrito.openstack/templates/osh/cinder.yml.j2

fix(openstack): add extra capabilities for netapp cinder-volume

fix(openstack): add extra capabilities for netapp cinder-volume

---

vars.yml.sample

fix: add the default containerd_registries_mirrors in vars.yml.sample

fix: add the default containerd_registries_mirrors in vars.yml.sample

---

landing.yml

fix(gnsh): do not run gnsh role when there is only one control node

fix(gnsh): do not run gnsh role when there is only one control node

---

roles/burrito.openstack/defaults/main.yml
roles/burrito.openstack/tasks/main.yml
vars.yml.sample

feature(openstack): make barbican installation optional

feature(openstack): make barbican installation optional

---

openstack-helm/cinder/templates/bin/_cinder-scheduler.sh.tpl
openstack-helm/cinder/templates/bin/_cinder-volume.sh.tpl
openstack-helm/nova/templates/bin/_nova-compute.sh.tpl
openstack-helm/nova/templates/bin/_nova-conductor.sh.tpl
openstack-helm/nova/templates/bin/_nova-scheduler.sh.tpl
roles/burrito.localrepo/defaults/main.yml
roles/burrito.netapp/tasks/main.yml
roles/burrito.openstack/templates/osh/nova.yml.j2
scripts/images.txt
vars.yml.sample

* override heartbeat_in_pthread to false in cinder-scheduler and cinder-volume; (jijisa@iorchard.net)
* fix(openstack): override heartbeat_in_pthread to false for nova-{compute,conductor,scheduler}; (jijisa@iorchard.net)
* Moved `notification_format: versioned` to notifications from DEFAULT. ; Removed `bdms_in_notifications: true` in notifications section. ; Removed AvailabilityZoneFilter from enabled_filters which is deprecated.; (jijisa@iorchard.net)
* changed kube_pods_subnet to the default value - 10.233.64.0/18; (jijisa@iorchard.net)

Fix openstack configuration

---

scripts/pfx_images.txt
vars.yml.sample

- upgrade csi-vxflexos to v2.11.0 which supports k8s v1.30.x
- Change powerflex glance store to file due to the bug (see https://bugs.launchpad.net/cinder/+bug/2068548)

include missing commit for powerflex
