iorchard/burrito

landing.yml
offline_vars.yml
roles/burrito.genesisregistry/defaults/main.yml
roles/burrito.genesisregistry/files/redhat/etc/systemd/system/genesis_registry.service
roles/burrito.genesisregistry/handlers/main.yml
roles/burrito.genesisregistry/tasks/main.yml
roles/burrito.genesisregistry/templates/redhat/etc/genesis_registry.conf.j2
roles/burrito.localrepo/defaults/main.yml
roles/burrito.localrepo/tasks/main.yml
roles/burrito.localrepo/templates/06-localrepo-svc.yml.j2
roles/burrito.localrepo/templates/redhat/etc/yum.repos.d/burrito.repo.j2
scripts/offline_services.sh
vars.yml.sample

Add genesis registry in landing playbook.
Its only purpose is to serve a registry image to local registry replicaset.

feature: genesis registry

---

roles/burrito.localrepo/defaults/main.yml
roles/burrito.localrepo/tasks/main.yml

copy /mnt/files to localrepo:/usr/share/nginx/html/

fix: copy-files-in-localrepo

---

kubespray/roles/kubernetes-apps/registry/templates/registry-rs.yml.j2
roles/burrito.localrepo/templates/05-localrepo-deploy.yml.j2

I added nodeSelector on local registry and repository pods spec.
For local repository, I changed strategy from rolling update to recreate since it mounts RWO PVC.

feature: local registry and repo pods on control nodes

---

kubespray/roles/burrito.openstack/templates/osh/cinder.yml.j2
vars.yml.sample

make cinder-backup deployment optional; add enable_cinder_backup variable (default: false) in vars.yml.sample

feature: make cinder-backup optional

---

vars.yml.sample

add storage_iface_name; move pod.replicas and public/cluster network variables to expert config block

feature: refactor vars.yml.sample

---

README.rst
README_offline.rst

update vars.yml content; put a note about network-node group

doc: update README files

---

README.rst
README_offline.rst

1. modified "README.rst & README_offline.rst" controller node name
2. modified cmdline output after 'bts' command in "README.rst & README_offline.rst"

modified README.rst typo

---

openstack-helm-infra/rabbitmq/templates/bin/_rabbitmq-start.sh.tpl

- modified_rabbitmq_start.sh.tpl
- updated btx nova_vnc_cert submodules

fix: update btx nova_vnc_cert submodules

---

registry.yml

copy iso image data to registry pod

copy iso image data to registry pod

---

netapp.yml

add when condition in netapp playbook so that it is skipped when netapp is not in storage_backends.

add when condition in netapp playbook

---

kubespray/roles/burrito.openstack/tasks/main.yml

put .btx.env in user .bashrc

---

kubespray/burrito.yml
kubespray/roles/burrito.openstack/tasks/main.yml

put .btx.env on all control nodes

put .btx.env on all control nodes

---

vars.yml.sample

upgrade btx

---

kubespray/roles/burrito.openstack/templates/osh/neutron.yml.j2
vars.yml.sample

Set up provider-only network if overlay_iface_name is null in vars.yml

feature: provider-only network setup

---

ansible.cfg.sample
hosts.sample
vars.yml.sample

remove ansible_* variables in inventory hosts; add remote_port in ansible.cfg.sample; add ansible_python_interpreter in vars.yml.sample

feature: simplify inventory hosts

---

hosts.sample
vars.yml.sample

fix: add ansible_python_interpreter=/usr/bin/python3 back to hosts.sample; remove ansible_python_interpreter in vars.yml.sample

fix: inventory hosts.sample and vars.yml.sample

---

docs/releases/1.1.0.rst

Add 1.1.0 release note file in docs/releases/

doc: add 1.1.0 release note file

---

docs/releases/1.1.0.rst

Update 1.1.0 release note file in docs/releases/

doc: update 1.1.0 release note file

---

scripts/images.txt
vars.yml.sample

feature: upgrade btx to 1.1.1

---

README.rst
README_offline.rst
vars.yml.sample

feature: support online-only installation

feature: support online-only installation

---

requirements.txt

Remove duplicate packages.

---

docs/releases/1.1.1.rst

doc: add 1.1.1 release note

---

README.rst
README_offline.rst
kubespray/roles/burrito.openstack/templates/osh/keystone.yml.j2
kubespray/roles/kubernetes-apps/metallb/templates/metallb.yml.j2
patches/00-patch.txt
patches/kubespray/roles/kubernetes/preinstall/tasks/0090-etchosts.yml
run.sh
vars.yml.sample

feature: add metallb installation option

feature: add metallb installation option

---

README.rst
README_offline.rst
scripts/images.txt

feature: add metallb images in scripts.images.txt; update README to include metallb configuration

feature: add metallb images and update README

---

ansible.cfg.sample
run.sh
scripts/clean_ceph.sh

feature: add ceph purge script; add library, role_path, module_utils in ansible.cfg.sample

feature: add ceph purge script

---

scripts/patch.sh

fix: add a missing scripts/patch.sh script

fix: add a missing scripts/patch.sh script

---

kubespray/roles/burrito.openstack/templates/osh/nova.yml.j2

fix: (openstack) modify nova novncproxy url in nova.yml.j2

fix: (openstack) modify nova novncproxy url in nova.yml.j2

---

README.rst
README_offline.rst
docs/releases/1.1.2.rst
scripts/changelog.sh

doc: update README and 1.1.2 release notes

doc: update README and 1.1.2 release notes

---

vars.yml.sample

doc: update comment on keepalived_vip_svc in vars.yml.sample

doc: update comment on keepalived_vip_svc in vars.yml.sample

---

docs/add_compute_node.rst
run.sh

피드백 내용을 참고하여 재 PR드립니다.
1.)add_compute_node.rst
전체 문서내용을 현재 기준으로 내용을 업데이트하였습니다.
2.) run.sh
피드백 받은 부분을 참고하여 확인하였으며 특이사항없음을 확인하였습니다.
검토부탁드립니다.
감사합니다.

modified compute node and run.sh

---

k8s.yml
run.sh

refactor: use kubespray/cluster.yml directly instead of k8s.yml; remove k8s.yml

refactor: use kubespray/cluster.yml in run.sh

---

README.rst
README_offline.rst
prepare.sh
run.sh

- feature: update prepare.sh to include all preparation tasks
- feature: add vault in run.sh; update README_offline.rst
- fix: install helm plugin into root home

feature: update prepare.sh to include all preparation tasks

---

openstack-helm/neutron/templates/bin/_neutron-linuxbridge-agent-init.sh.tpl

enhance: do not even create ml2-local-ip.ini if vxlan is disabled

enhance: not create ml2-local-ip.ini if vxlan is disabled

---

docs/releases/1.1.3.rst

Add 1.1.3 release note file in docs/releases/

doc: add 1.1.3 release note file

---

docs/install.rst
docs/install_offline.rst

doc: update install documents

---

docs/install.rst
docs/install_offline.rst
hosts.sample

fix: move back to network-node to edit are in hosts.sample; update install documents

fix: move back to network-node to edit are in hosts.sample

---

docs/install.rst

doc: update online install document

doc: update online install document

---

docs/install.rst
docs/install_offline.rst

doc: fix typo in install.rst and install_offline.rst

doc: fix typo in install.rst and install_offline.rst

---

scripts/images.txt

fix: modify btx image tag to 1.2.0 in scripts/images.txt

fix: modify btx image tag to 1.2.0 in scripts/images.txt

---

roles/burrito.keepalived/files/redhat/etc/keepalived/check_proxy

enhance: (keepalived) remove sudo in check_proxy script since keepalived is already running as root

enhance: (keepalived) remove sudo in check_proxy script since keepalived is already running as root

---

docs/releases/1.2.0.rst
docs/source/conf.py
docs/source/index.rst
docs/source/install/install_offline.rst

- doc: update readthedocs documents
- doc: add 1.2.0 release note

doc: add 1.2.0 release note

---

ceph-csi.yml
ha.yml
hosts.sample
roles/burrito.ceph-csi/templates/00-csi-configmap.yml.j2
roles/burrito.haproxy/templates/redhat/etc/haproxy/haproxy.cfg.j2
roles/burrito.rgw-user/templates/s3cfg.j2
vars.yml.sample

refactor: use storage_iface_name to get storage ip address

refactor: use storage_iface_name to get storage ip address

---

patches/kubespray/roles/kubernetes-apps/registry/templates/registry-rs.yml.j2

fix: add the missing registry patch directory

fix: add the missing registry patch directory

---

scripts/burrito.sh

fix: scripts/burrito.sh; replace KUBESPRAY_DIR into TOP_DIR

fix: burrito.sh script

---

scripts/images.txt
vars.yml.sample

fix: check ip range in burrito-test.sh script on btx

feature: upgrade btx to 1.2.1

---

ceph-csi.yml
roles/burrito.ceph-csi/defaults/main.yml
roles/burrito.ceph-csi/tasks/main.yml
vars.yml.sample

fix: add registry_enabled in when condition

fix: add registry_enabled in when condition

---

burrito.yml
roles/burrito.ceph-csi/tasks/main.yml
roles/burrito.genesisregistry/defaults/main.yml
roles/burrito.genesisregistry/files/redhat/etc/systemd/system/genesis_registry.service
roles/burrito.genesisregistry/tasks/main.yml
roles/burrito.keepalived/tasks/setup.yml
roles/burrito.localrepo/tasks/main.yml
roles/burrito.openstack/templates/osh_infra/ceph-provisioners.yml.j2

fix: add k8s images to genesis registry

fix: add k8s images to genesis registry

---

k8spatch.yml
roles/burrito.genesisregistry/tasks/main.yml

fix: add 5 seconds pause on restarting kubelet

fix: add 5 seconds pause on restarting kubelet

---

k8spatch.yml
roles/burrito.genesisregistry/tasks/main.yml

fix: update pause tasks

---

openstack-helm/cinder/templates/configmap-etc.yaml
roles/burrito.openstack/templates/osh/cinder.yml.j2

feature: add the in-use volume migration support in cinder

feature: add the in-use volume migration support in cinder

---

checklist.yml
preflight.yml
prepare.sh
vars.yml.sample

feature: add checklist in preflight playbook

feature: add checklist in preflight playbook

---

patches/10-patch-kubespray-etcd-template-etcd-host-service.txt
patches/kubespray/roles/etcd/templates/etcd-host.service.j2
vars.yml.sample

feature: patch to set high scheduling priority to etcd service

feature: patch to set high scheduling priority to etcd service

---

scripts/create_tarball.sh

feature: include tag and commit id info in release tarball

feature: include tag and commit id info in release tarball

---

vars.yml.sample

fix: containerd_insecure_registries in vars.yml.sample

fix: containerd_insecure_registries in vars.yml.sample

---

prepare.sh

feature: back up config files when prepare.sh script runs

feature: back up config files when prepare.sh script runs

---

VERSIONS

feature: add VERSIONS file

---

patches/11-patch-kubespray-calico-templates-cni-calico-conflist.txt
patches/kubespray/roles/network_plugin/calico/templates/cni-calico.conflist.j2
vars.yml.sample

feature: change calico subnet mask

feature: change calico subnet mask

---

prepare.sh

feature: skip copying config files if exist

feature: skip copying config files if exist

---

scripts/create_tarball.sh

feature: add burrito version dynamically to VERSIONS in create_tarball script

feature: add burrito version dynamically to VERSIONS in create_tarball script

---

roles/burrito.openstack/templates/osh/neutron.yml.j2

feature: add Network QoS parameters in neutron

feature: add Network QoS parameters in neutron

---

vars.yml.sample

fix: set target_size_ratio to 0 in vars.yml.sample

fix: set target_size_ratio to 0 in vars.yml.sample

---

preflight.yml
roles/burrito.ntp/defaults/main.yml
roles/burrito.ntp/tasks/check.yml
roles/burrito.ntp/tasks/main.yml

feature: wait until ntp is synced

feature: wait until ntp is synced

---

roles/burrito.ntp/tasks/check.yml
roles/burrito.ntp/tasks/rocky.yml

feature: add ntp sync check for the first control node

feature: add ntp sync check for the first control node

---

vars.yml.sample

feature: add ssh_port variable in vars.yml.sample

feature: add ssh_port variable in vars.yml.sample

---

checklist.yml

fix: check storage ip addresses are set checklist

fix: check storage ip addresses are set checklist

---

roles/burrito.powerflex/tasks/install.yml
roles/burrito.powerflex/templates/vxflexos-values.yml.j2

fix: Set vxflexos controllerCount to pod.replicas

fix: Set vxflexos controllerCount to pod.replicas

---

powerflex_vars.yml.tpl

update powerflex variables template file

update powerflex variables template file

---

roles/burrito.openstack/defaults/main.yml
roles/burrito.openstack/templates/osh/barbican.yml.j2
roles/burrito.openstack/templates/osh/cinder.yml.j2
roles/burrito.openstack/templates/osh/glance.yml.j2
roles/burrito.openstack/templates/osh/keystone.yml.j2
roles/burrito.openstack/templates/osh/neutron.yml.j2
roles/burrito.openstack/templates/osh/nova.yml.j2

feature: set openstack rabbitmq queues to quorum

feature: set openstack rabbitmq queues to quorum

---

roles/burrito.genesisregistry/handlers/main.yml
roles/burrito.genesisregistry/tasks/main.yml
roles/burrito.localrepo/handlers/main.yml
roles/burrito.localrepo/tasks/main.yml
roles/burrito.powerflex/handlers/main.yml
roles/burrito.powerflex/tasks/config.yml

feature: reload haproxy instead of restart

feature: reload haproxy instead of restart

---

vars.yml.sample

feature: adjust rabbitmq PVC size to 10Gi

feature: adjust rabbitmq PVC size to 10Gi

---

vars.yml.sample

feature: set sysctl file for k8s kernel parameters

feature: set sysctl file for k8s kernel parameters

---

roles/burrito.genesisregistry/tasks/main.yml
roles/burrito.powerflex/defaults/main.yml
roles/burrito.powerflex/tasks/config.yml
roles/burrito.powerflex/templates/redhat/etc/haproxy/conf.d/powerflex.cfg.j2

feature(powerflex): Create powerflex haproxy LB file instead of add the section in haproxy.cfg.

feature(powerflex): Create powerflex haproxy LB file instead of add the section in haproxy.cfg.

---

roles/burrito.powerflex/tasks/cluster.yml
roles/burrito.powerflex/tasks/setup.yml

feature(powerflex): Add until/retries/delay for changing mdm password and sds devices tasks

feature(powerflex): Add until/retries/delay for changing mdm password and sds devices tasks

---

samples/busybox-deploy.yml
samples/web-sts.yml

feature: add pod sample yaml files

feature: add pod sample yaml files

---

roles/burrito.genesisregistry/tasks/main.yml

fix: no need to patch registry pod since registry deployment is patched

fix: no need to patch registry pod since registry deployment is patched

---

roles/burrito.genesisregistry/tasks/main.yml
vars.yml.sample

feature: add tls-cipher-suite in kube-apiserver

feature: add tls-cipher-suite in kube-apiserver

---

vars.yml.sample

fix: add comment about tls_cipher_suites in vars.yml.sample

fix: add comment about tls_cipher_suites in vars.yml.sample

---

roles/burrito.openstack/templates/osh/barbican.yml.j2
roles/burrito.openstack/templates/osh/placement.yml.j2

fix(openstack): add replicas to barbican and placement api

fix(openstack): add replicas to barbican and placement api

---

openstack-helm/cinder/templates/deployment-volume.yaml
openstack-helm/cinder/values.yaml
openstack-helm/glance/templates/deployment-api.yaml
openstack-helm/glance/values.yaml
roles/burrito.openstack/templates/osh/cinder.yml.j2
roles/burrito.openstack/templates/osh/glance.yml.j2
vars.yml.sample

feature(openstack): add PVC to cinder-volume and glance-api

feature(openstack): add PVC to cinder-volume and glance-api

---

scripts/clean_openstack.sh

fix: add inventory and vault password parameter in clean_openstack.sh script

fix: add inventory and vault password parameter in clean_openstack.sh script

---

scripts/clean_openstack.sh

fix: remove inventory and vault parameters in clean_openstack.sh script

fix: remove inventory and vault parameters in clean_openstack.sh script

---

scripts/clean_k8s.sh
scripts/clean_openstack.sh
vars.yml.sample

feature(k8s): bind 127.0.0.1 for kube-controller-manager and kube-scheduler

feature(k8s): bind 127.0.0.1 for kube-controller-manager and kube-scheduler

---

openstack-helm/cinder/templates/deployment-volume.yaml
openstack-helm/cinder/templates/pvc-conversion.yaml
openstack-helm/cinder/values.yaml
openstack-helm/glance/templates/deployment-api.yaml
openstack-helm/glance/templates/pvc-nginx-client-tmp.yaml
openstack-helm/glance/values.yaml
roles/burrito.openstack/templates/osh/cinder.yml.j2
roles/burrito.openstack/templates/osh/glance.yml.j2
vars.yml.sample

fix(openstack): Deployment PVC support for cinder-volume and glance-api

fix(openstack): Deployment PVC support for cinder-volume and glance-api

---

openstack-helm-infra/mariadb/values.yaml

feature(mariadb): disable local_infile in mariadb

feature(mariadb): disable local_infile in mariadb

---

vars.yml.sample

fix(vars): fix typo in cinder_vol_deploy_type_map variable

fix(vars): fix typo in cinder_vol_deploy_type_map variable

---

checklist.yml

fix(preflight): fix keepalived_vip_svc in service network range check

fix(preflight): fix keepalived_vip_svc in service network range check

---

netapp_vars.yml.tpl

fix(netapp): fix nfsMountOptions for broader compatibility

fix(netapp): fix nfsMountOptions for broader compatibility

---

VERSIONS

doc: update VERSIONS

---

roles/burrito.openstack/templates/osh/cinder.yml.j2
scripts/images.txt

set verify_glance_signatures to disabled not to check glance signatures since it still has a bug.

fix(openstack): set verify_glance_signatures to disabled

---

vars.yml.sample

fix: single_osd_node variable to set osd_crush_chooseleaf_type variable correctly

fix: single_osd_node variable to set osd_crush_chooseleaf_type variable correctly

---

hosts_hitachi.sample

add host inventory sample for hitachi storage

add host inventory sample for hitachi storage

---

hosts_hitachi.sample

fix: modify hitachi host inventory sample file

fix: modify hitachi host inventory sample file

---

roles/burrito.openstack/templates/osh/nova.yml.j2

feature(openstack): disable instance_usage_audit in nova conf

feature(openstack): disable instance_usage_audit in nova conf

---

burrito.yml
roles/burrito.ceph-csi/tasks/main.yml
roles/burrito.openstack/templates/osh/nova.yml.j2
roles/burrito.rgw-user/defaults/main.yml
run.sh
scripts/images.txt
vars.yml.sample

feature: remove cloudpc-related tasks

feature: remove cloudpc-related tasks

---

openstack-helm-infra/mariadb/values.yaml
roles/burrito.openstack/templates/osh_infra/mariadb.yml.j2
scripts/images.txt

feature: upgrade mariadb to 10.6.16

feature: upgrade mariadb

---

descheduler.yml
patch.yml
roles/burrito.descheduler/README.md
roles/burrito.descheduler/defaults/main.yml
roles/burrito.descheduler/files/configmap.yaml
roles/burrito.descheduler/files/rbac.yaml
roles/burrito.descheduler/meta/main.yml
roles/burrito.descheduler/tasks/main.yml
roles/burrito.descheduler/templates/deployment.yaml.j2

feature(k8s): add descheduler

---

roles/burrito.ceph/tasks/bootstrap.yml

feature(ceph): check if host is prepared

feature(ceph): check if host is prepared

---

scripts/k8s_app.sh
scripts/k8s_app.yml
vars.yml.sample

feature(k8s): override nodeSelector in coredns and calico controller

feature(k8s): override nodeSelector in coredns and calico controller

---

roles/burrito.genesisregistry/defaults/main.yml
roles/burrito.genesisregistry/tasks/calico_patch.yml
roles/burrito.genesisregistry/tasks/main.yml

fix(k8s): add calico images in genesis registry

fix(k8s): add calico images in genesis registry

---

roles/burrito.descheduler/templates/deployment.yaml.j2
scripts/images.txt

fix(k8s): descheduler offline support

fix(k8s): descheduler offline support

---

roles/burrito.genesisregistry/tasks/main.yml
vars.yml.sample

fix(burrito): modify genesis registry task name

fix(burrito): modify genesis registry task name

---

landing.yml
roles/burrito.asklepios/README.md
roles/burrito.asklepios/defaults/main.yml
roles/burrito.asklepios/files/rbac.yaml
roles/burrito.asklepios/meta/main.yml
roles/burrito.asklepios/tasks/main.yml
roles/burrito.asklepios/templates/configmap.yaml.j2
roles/burrito.asklepios/templates/deployment.yaml.j2
scripts/images.txt

feature(asklepios): auto-healing service when node is not ready

feature(asklepios): auto-healing service

---

landing.yml
vars.yml.sample

fix(gnsh): remove gnsh since asklepios replaces it

fix(gnsh): remove gnsh since asklepios replaces it

---

group_vars.sample/all/asklepios.yml

feature(asklepios): add asklepios group vars file

feature(asklepios): add asklepios group vars file

---

vars.yml.sample

feature(k8s): upgrade k8s to 1.29.2

feature(k8s): upgrade k8s to 1.29.2

---

roles/burrito.descheduler/defaults/main.yml
roles/burrito.descheduler/files/configmap.yaml
scripts/images.txt

feature(k8s): upgrade descheduler to v0.29.0

feature(k8s): upgrade descheduler to v0.29.0

---

group_vars.sample/all/asklepios.yml

update asklepios group vars

---

descheduler.yml
landing.yml
patch.yml
roles/burrito.ceph/defaults/main.yml
roles/burrito.ceph/tasks/main.yml
roles/burrito.ceph/tasks/status.yml

feature(ceph): add health check

feature(ceph): add health check

---

roles/burrito.genesisregistry/tasks/main.yml

fix(genesis_registry): add when condition in patch asklepios

fix(genesis_registry): add when condition in patch asklepios

---

VERSIONS
offline_vars.yml
roles/burrito.netapp/defaults/main.yml
scripts/images.txt
scripts/netapp_images.txt
vars.yml.sample

feature(netapp): upgrade trident to 24.02

feature(netapp): upgrade trident to 24.02

---

openstack-helm/nova/values.yaml
roles/burrito.descheduler/defaults/main.yml

feature(openstack): enhance high availability

feature(openstack): enhance high availability

---

roles/burrito.openstack/templates/btx.yml.j2
vars.yml.sample

feature(k8s): make AlwaysPullImages plugin optional

feature(k8s): make AlwaysPullImages plugin optional

---

openstack-helm/nova/values.yaml
patch.yml
roles/burrito.openstack/templates/osh/nova.yml.j2
roles/burrito.openstack/templates/osh/placement.yml.j2

feature(openstack): ha tuning

---

group_vars.sample/all/asklepios.yml
roles/burrito.asklepios/files/rbac.yaml
roles/burrito.asklepios/templates/configmap.yaml.j2
scripts/images.txt
vars.yml.sample

feature(asklepios): upgrade to 0.2.0

feature(asklepios): upgrade to 0.2.0

---

roles/burrito.ceph/templates/cluster.yml.j2

fix(ceph): remove count from mon and mgr

fix(ceph): remove count from mon and mgr

---

ansible.cfg.sample
roles/burrito.openstack/templates/osh/glance.yml.j2
scripts/k8s_app.sh
scripts/k8s_app.yml
vars.yml.sample

fix(netapp): upgrade trident installer

fix(netapp): upgrade trident installer

---

roles/burrito.asklepios/defaults/main.yml

update asklepios variables in burrito.asklepios role

update asklepios variables in burrito.asklepios role

---

scripts/kubelet-csr-approver-index.yaml

fix(k8s): urls in kubelet-csr-approver-index.yaml was wrong; it is fixed

fix(k8s): urls in kubelet-csr-approver-index.yaml was wrong; it is fixed

---

scripts/changelog.sh

modify changelog.sh

---

vars.yml.sample

config(k8s): adjust image gc high/low threshold

config(k8s): adjust image gc high/low threshold

---

roles/burrito.keepalived/templates/redhat/etc/keepalived/keepalived.conf.j2

fix(ha): change keepalived state when haproxy is stopped

fix(ha): change keepalived state when haproxy is stopped

---

roles/burrito.ceph/templates/cluster.yml.j2
roles/burrito.netapp/tasks/main.yml
roles/burrito.openstack/templates/osh/cinder.yml.j2

* feature(cinder): add image upload use cinder backend config
* feature(netapp): add nfsclient.conf in burrito.netapp role
* feature(ceph) add labels on each node

merge begonia

---

patches/12-patch-kubespray-control-plane-kubeadm-secondary.txt
patches/12-patch-kubespray-control-plane-kubeadm-upgrade.txt
patches/kubespray/roles/kubernetes/control-plane/tasks/kubeadm-secondary.yml
patches/kubespray/roles/kubernetes/control-plane/tasks/kubeadm-upgrade.yml
roles/burrito.cert-manager/tasks/cert_manager.yml
vars.yml.sample

fix some k8s issues

---

checklist.yml
prepare.sh
run.sh

fix some issues

---

roles/burrito.asklepios/defaults/main.yml
roles/burrito.asklepios/tasks/main.yml
scripts/milestone.sh

solved issues about k8s deployment and upgrade

solved issues about k8s deployment and upgrade

---

roles/burrito.genesisregistry/defaults/main.yml
roles/burrito.genesisregistry/tasks/powerflex_patch.yml
roles/burrito.powerflex/defaults/main.yml
roles/burrito.powerflex/tasks/csi.yml
roles/burrito.powerflex/templates/vxflexos-values.yml.j2
run.sh
scripts/pfx_images.txt

fix some issues with powerflex

fix some issues with powerflex

---

roles/burrito.openstack/templates/osh/glance.yml.j2
run.sh
vars.yml.sample

* add pfx_sdc_version variable in vars.yml.sample
* set glance-api replicas to 1 if default backend is file
* change ownership of helm plugin directory in run.sh script

add pfx_sdc_version variable in vars.yml.sample
